# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streem/room/ar/storage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from streem.api import common_models_pb2 as streem_dot_api_dot_common__models__pb2
from streem.room import rooms_pb2 as streem_dot_room_dot_rooms__pb2
from streem.room.ar import common_pb2 as streem_dot_room_dot_ar_dot_common__pb2
from streem.room.ar import tracking_pb2 as streem_dot_room_dot_ar_dot_tracking__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cstreem/room/ar/storage.proto\x12\x0estreem.room.ar\x1a\x1estreem/api/common_models.proto\x1a\x17streem/room/rooms.proto\x1a\x1bstreem/room/ar/common.proto\x1a\x1dstreem/room/ar/tracking.proto\"\xaf\x02\n\x0cMeshArtifact\x12-\n\ntrackables\x18\x01 \x03(\x0b\x32\x19.streem.room.ar.Trackable\x12\x43\n\x11mesh_enhancements\x18\x02 \x03(\x0b\x32(.streem.room.ar.MeshArtifact.Enhancement\x1a\xaa\x01\n\x0b\x45nhancement\x12\x19\n\x11texture_jpeg_data\x18\x01 \x01(\x0c\x12,\n\x11\x63\x61mera_intrinsics\x18\x02 \x01(\x0b\x32\x11.CameraIntrinsics\x12+\n\x11\x63\x61mera_dimensions\x18\x03 \x01(\x0b\x32\x10.streem.api.Size\x12%\n\x0b\x63\x61mera_pose\x18\x04 \x01(\x0b\x32\x10.streem.api.Pose\"\xda\x01\n\x0c\x44\x65pthMapData\x12 \n\tdepth_map\x18\x01 \x01(\x0b\x32\r.VectorBuffer\x12%\n\x0e\x63onfidence_map\x18\x02 \x01(\x0b\x32\r.VectorBuffer\x12\x37\n\x08\x65ncoding\x18\x03 \x01(\x0e\x32%.streem.room.ar.DepthMapData.Encoding\"H\n\x08\x45ncoding\x12\x14\n\x10\x45NCODING_INVALID\x10\x00\x12\x10\n\x0c\x45NCODING_IOS\x10\x01\x12\x14\n\x10\x45NCODING_ANDROID\x10\x02\"\x91\x01\n\x14LayoutEstimationData\x12+\n\x14layout_edge_vertices\x18\x01 \x01(\x0b\x32\r.VectorBuffer\x12\x30\n\x12triangulated_floor\x18\x02 \x01(\x0b\x32\x14.streem.room.ar.Mesh\x12\x1a\n\x12\x61rea_square_meters\x18\x03 \x01(\x02\x42J\n&pro.streem.commons.model.proto.room.arB\x0cStorageProtoP\x01\xba\x02\x0fStreem_Room_Ar_b\x06proto3')



_MESHARTIFACT = DESCRIPTOR.message_types_by_name['MeshArtifact']
_MESHARTIFACT_ENHANCEMENT = _MESHARTIFACT.nested_types_by_name['Enhancement']
_DEPTHMAPDATA = DESCRIPTOR.message_types_by_name['DepthMapData']
_LAYOUTESTIMATIONDATA = DESCRIPTOR.message_types_by_name['LayoutEstimationData']
_DEPTHMAPDATA_ENCODING = _DEPTHMAPDATA.enum_types_by_name['Encoding']
MeshArtifact = _reflection.GeneratedProtocolMessageType('MeshArtifact', (_message.Message,), {

  'Enhancement' : _reflection.GeneratedProtocolMessageType('Enhancement', (_message.Message,), {
    'DESCRIPTOR' : _MESHARTIFACT_ENHANCEMENT,
    '__module__' : 'streem.room.ar.storage_pb2'
    # @@protoc_insertion_point(class_scope:streem.room.ar.MeshArtifact.Enhancement)
    })
  ,
  'DESCRIPTOR' : _MESHARTIFACT,
  '__module__' : 'streem.room.ar.storage_pb2'
  # @@protoc_insertion_point(class_scope:streem.room.ar.MeshArtifact)
  })
_sym_db.RegisterMessage(MeshArtifact)
_sym_db.RegisterMessage(MeshArtifact.Enhancement)

DepthMapData = _reflection.GeneratedProtocolMessageType('DepthMapData', (_message.Message,), {
  'DESCRIPTOR' : _DEPTHMAPDATA,
  '__module__' : 'streem.room.ar.storage_pb2'
  # @@protoc_insertion_point(class_scope:streem.room.ar.DepthMapData)
  })
_sym_db.RegisterMessage(DepthMapData)

LayoutEstimationData = _reflection.GeneratedProtocolMessageType('LayoutEstimationData', (_message.Message,), {
  'DESCRIPTOR' : _LAYOUTESTIMATIONDATA,
  '__module__' : 'streem.room.ar.storage_pb2'
  # @@protoc_insertion_point(class_scope:streem.room.ar.LayoutEstimationData)
  })
_sym_db.RegisterMessage(LayoutEstimationData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n&pro.streem.commons.model.proto.room.arB\014StorageProtoP\001\272\002\017Streem_Room_Ar_'
  _MESHARTIFACT._serialized_start=166
  _MESHARTIFACT._serialized_end=469
  _MESHARTIFACT_ENHANCEMENT._serialized_start=299
  _MESHARTIFACT_ENHANCEMENT._serialized_end=469
  _DEPTHMAPDATA._serialized_start=472
  _DEPTHMAPDATA._serialized_end=690
  _DEPTHMAPDATA_ENCODING._serialized_start=618
  _DEPTHMAPDATA_ENCODING._serialized_end=690
  _LAYOUTESTIMATIONDATA._serialized_start=693
  _LAYOUTESTIMATIONDATA._serialized_end=838
# @@protoc_insertion_point(module_scope)
